site_name: Gluu Servers
site_description: An SSO, Federation and API Access Management suite
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs
theme: spacelab 

theme_dir: ./theme/mkdocs/
theme_center_lead: false
include_search: true

pages:

# Home Page
- ['index.md', 'Home']

# Admin Guide Sections
- ['admin-guide/introduction/index.md', 'Admin Guide', 'Introduction']
- ['admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['admin-guide/gluu-server-operations/index.md', 'Admin Guide', 'Gluu Server Operations']
- ['admin-guide/custom-look/index.md', 'Admin Guide', 'Customizing Look and Feel']
- ['admin-guide/certificates/index.md', 'Admin Guide', 'Certificates']
- ['admin-guide/user-management/index.md', 'Admin Guide', 'User Management']
- ['admin-guide/authentication/index.md', 'Admin Guide', 'Authentication']
- ['admin-guide/saml/index.md', 'Admin Guide', 'SAML']
- ['admin-guide/openid-connect/index.md', 'Admin Guide', 'OpenID Connect']
- ['admin-guide/uma/index.md', 'Admin Guide', 'UMA']
- ['admin-guide/mod-ox/index.md', 'Admin Guide', 'Mod OX']
- ['admin-guide/interception-scripts/index.md', 'Admin Guide', 'Interception Scripts']
#- ['admin-guide/multiparty-federation/index.md', 'Admin Guide', 'MultiParty Federation']
- ['admin-guide/oxPush/index.md', 'Admin Guide', 'oxPush']
- ['admin-guide/cluster/index.md', 'Admin Guide', 'HA Clusters']

# Reference sections
- ['reference/configuration/index.md', 'Reference', 'Configuration']
- ['reference/oxTrust/index.md', 'Reference', 'oxTrust User Interface']
- ['reference/ldap/index.md', 'Reference', 'LDAP Configuration']
- ['reference/lib/index.md', 'Reference', 'Libraries']
- ['reference/api/index.md', 'Reference', 'APIs']

# Sub pages of References / API
- ['reference/api/oic-authorization.md', '**HIDDEN**']
- ['reference/api/oic-token.md', '**HIDDEN**']
- ['reference/api/oic-userinfo.md', '**HIDDEN**']
- ['reference/api/oic-register-client.md', '**HIDDEN**']
- ['reference/api/oic-end-session.md', '**HIDDEN**']

- ['reference/api/uma-discovery.md', '**HIDDEN**']

- ['reference/api/id-generation.md', '**HIDDEN**']


# Articles
- ['articles/gluu-server-ce.md', 'Articles', 'Try Gluu Server CE - Quickstart']
- ['./articles/apache-saml.md', 'Articles', 'Apache SAML']
- ['articles/java-saml.md', 'Articles', 'Java SAML']
- ['articles/google-saml.md', 'Articles', 'Google SAML']
- ['articles/apache-oauth2.md', 'Articles', 'Apache OpenID Connect / UMA']
- ['articles/js-connect.md', 'Articles', 'JavaScript OpenID Connect RP']
- ['articles/java-connect.md', 'Articles', 'Java OpenID Connect RP']
- ['articles/scim-client.md', 'Articles', 'Java SCIM client']
- ['articles/benchmarking.md', 'Articles', 'Gluu Server Benchmark']
- ['articles/custom-attributes.md', 'Articles', 'Adding Custom User Attributes']

# Sub Pages of introduction 
- ['admin-guide/introduction/architecture.md', '**HIDDEN**']
- ['admin-guide/introduction/design-goals.md', '**HIDDEN**']
- ['admin-guide/introduction/gluu-server-mission.md', '**HIDDEN**']
- ['admin-guide/introduction/history.md', '**HIDDEN**']
- ['admin-guide/introduction/licenses.md', '**HIDDEN**']

# Sub Pages of Admin Guide / installation
- ['admin-guide/installation/ubuntu.md', '**HIDDEN**']
- ['admin-guide/installation/centos.md', '**HIDDEN**']
- ['admin-guide/installation/juju.md', '**HIDDEN**']

# Sub Pages of Admin Guide / Gluu Server Operations
- ['admin-guide/gluu-server-operations/start-stop-chroot.md', '**HIDDEN**']
- ['admin-guide/gluu-server-operations/restart-services-within-chroot.md', '**HIDDEN**']

# Sub Pages of Admin Guide / Certificates
- ['admin-guide/certificates/https.md', '**HIDDEN**']
- ['admin-guide/certificates/saml.md', '**HIDDEN**']
- ['admin-guide/certificates/openid.md', '**HIDDEN**']

# Sub pages of Admin Guide / User-Management
- ['admin-guide/user-management/scim.md', '**HIDDEN**']
- ['admin-guide/user-management/ldap-sync.md', '**HIDDEN**']
- ['admin-guide/user-management/registration.md', '**HIDDEN**']
- ['admin-guide/user-management/local-user-mgt.md', '**HIDDEN**']

# Sub pages of Admin Guide / Authentication
- ['admin-guide/authentication/ldap.md', '**HIDDEN**']
- ['admin-guide/authentication/custom.md', '**HIDDEN**']
- ['admin-guide/authentication/oxPush.md', '**HIDDEN**']
- ['admin-guide/authentication/saml.md', '**HIDDEN**']
- ['admin-guide/authentication/cas.md', '**HIDDEN**']
- ['admin-guide/authentication/google.md', '**HIDDEN**']
- ['admin-guide/authentication/duo.md', '**HIDDEN**']
- ['admin-guide/authentication/toopher.md', '**HIDDEN**']
- ['admin-guide/authentication/tips.md', '**HIDDEN**']

# Sub pages of Admin Guide / SAML
- ['admin-guide/saml/outbound-saml.md', '**HIDDEN**']
- ['admin-guide/saml/inbound-saml.md', '**HIDDEN**']
- ['admin-guide/saml/saml-sp-configuration.md', '**HIDDEN**']

# Sub pages of Admin Guide / UMA
- ['admin-guide/uma/introduction.md', '**HIDDEN**']

# Sub pages of Admin Guide / UMA 
- ['admin-guide/uma/discovery.md', '**HIDDEN**']
- ['admin-guide/uma/resource-registration.md', '**HIDDEN**']
- ['admin-guide/uma/policy.md', '**HIDDEN**']
- ['admin-guide/uma/uma-scopes.md', '**HIDDEN**']
- ['admin-guide/uma/uma-profile.md', '**HIDDEN**']

# Sub pages of Admin Guide / Interception Scripts 
- ['admin-guide/interception-scripts/authentication.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/authorization.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/id-generation.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/attribute-transformation.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/post-registration.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/pre-registration.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/logout.md', '**HIDDEN**']
- ['admin-guide/interception-scripts/saml-discovery.md', '**HIDDEN**']

# Sub pages of Admin Guide / oxPush
- ['admin-guide/oxPush/cordova-app.md', '**HIDDEN**']
- ['admin-guide/oxPush/oxPush-server.md', '**HIDDEN**']
- ['admin-guide/oxPush/oxPush-crypto.md', '**HIDDEN**']

# Supb pgaes of Admin Guid / GLUU Cluster
- ['admin-guide/cluster/geo_cluster.md', '**HIDDEN**']

# Sub pages of Multiparty Federation 
- ['admin-guide/multiparty-federation/saml-federation.md', '**HIDDEN**']
- ['admin-guide/multiparty-federation/oauth2-federation.md', '**HIDDEN**']
- ['admin-guide/multiparty-federation/federation-public-website.md', '**HIDDEN**']

- ['reference/lib/openid-connect.md', '**HIDDEN**']
- ['reference/lib/uma.md', '**HIDDEN**']
- ['reference/lib/scim.md', '**HIDDEN**']
- ['reference/lib/saml.md', '**HIDDEN**']

# Sub pages of Reference / LDAP
- ['reference/ldap/schema.md', '**HIDDEN**']
- ['reference/ldap/namespace.md', '**HIDDEN**']
- ['reference/ldap/indexing.md', '**HIDDEN**']
- ['reference/ldap/replication.md', '**HIDDEN**']
- ['reference/ldap/config.md', '**HIDDEN**']

# Sub pages of Reference / Configuration
- ['reference/configuration/oxTrust.md', '**HIDDEN**']
- ['reference/configuration/asimba.md', '**HIDDEN**']

# Sub pages of Reference / Configuration
- ['reference/oxTrust/configuration.md', '**HIDDEN**']
- ['reference/oxTrust/oauth2.md', '**HIDDEN**']
- ['reference/oxTrust/personal.md', '**HIDDEN**']
- ['reference/oxTrust/saml.md', '**HIDDEN**']
- ['reference/oxTrust/users.md', '**HIDDEN**']
